import { DataType } from '$lib/sav/dataType';
import {
  ADDRESS_FORM,
  AGE_TYPE,
  AGE_TYPE_OPTIONAL,
  FAMILY_RELATION,
  CLOTH_STYLE_GENDER,
  LANGUAGE,
  VOICE_PRESET,
  MII_GENDER,
  FEELING,
  OWNERSHIP,
  PRONOUN,
  RELATION,
  WORD_KIND,
} from './enumOptions';

const _MII_SCHEMA = {
  Childcare: {
    Pending: {
      CharInfoEx: { hash: 0xe0d319f5, type: DataType.Binary },
      CharacterParam: {
        Activeness: { hash: 0x3c49763d, type: DataType.Int },
        Audaciousness: { hash: 0xf3606969, type: DataType.Int },
        Commonsense: { hash: 0xa7e38eed, type: DataType.Int },
        Gaiety: { hash: 0xa9bc9d8b, type: DataType.Int },
        Sociability: { hash: 0x89c78941, type: DataType.Int },
      },
      Gender: { hash: 0xefd377b2, type: DataType.Enum, options: MII_GENDER },
      HabitOwnInfo: {
        BlinkLot: {
          IsChecked: { hash: 0x0f581f56, type: DataType.Bool },
          IsOwn: { hash: 0x67ae4cbd, type: DataType.Bool },
          State: { hash: 0x8751dc34, type: DataType.Enum, options: OWNERSHIP },
        },
        BreakGas: {
          IsChecked: { hash: 0x0f1a5251, type: DataType.Bool },
          IsOwn: { hash: 0x6784d3a0, type: DataType.Bool },
          State: { hash: 0x7d5927d6, type: DataType.Enum, options: OWNERSHIP },
        },
        ChangeCloth: {
          IsChecked: { hash: 0xf84b7e52, type: DataType.Bool },
          IsOwn: { hash: 0xebf8ca58, type: DataType.Bool },
          State: { hash: 0x40c98079, type: DataType.Enum, options: OWNERSHIP },
        },
        Chicken: {
          IsChecked: { hash: 0xdc593de2, type: DataType.Bool },
          IsOwn: { hash: 0x783a56ea, type: DataType.Bool },
          State: { hash: 0xdb61b200, type: DataType.Enum, options: OWNERSHIP },
        },
        EatCarefully: {
          IsChecked: { hash: 0xe9665718, type: DataType.Bool },
          IsOwn: { hash: 0x76d18031, type: DataType.Bool },
          State: { hash: 0xc29fc39c, type: DataType.Enum, options: OWNERSHIP },
        },
        EatCrisp: {
          IsChecked: { hash: 0x67d66f5f, type: DataType.Bool },
          IsOwn: { hash: 0xb754bb23, type: DataType.Bool },
          State: { hash: 0x9c9f4bd8, type: DataType.Enum, options: OWNERSHIP },
        },
        EatCute: {
          IsChecked: { hash: 0xff6fe51f, type: DataType.Bool },
          IsOwn: { hash: 0x3366c93f, type: DataType.Bool },
          State: { hash: 0x7f60d992, type: DataType.Enum, options: OWNERSHIP },
        },
        EatElegantly: {
          IsChecked: { hash: 0x2a5bf4cb, type: DataType.Bool },
          IsOwn: { hash: 0x3b64e8c9, type: DataType.Bool },
          State: { hash: 0xafdfb727, type: DataType.Enum, options: OWNERSHIP },
        },
        EatMouthful: {
          IsChecked: { hash: 0x4b00a91e, type: DataType.Bool },
          IsOwn: { hash: 0xb7c6cc33, type: DataType.Bool },
          State: { hash: 0x78adc243, type: DataType.Enum, options: OWNERSHIP },
        },
        EatSecretly: {
          IsChecked: { hash: 0x04817255, type: DataType.Bool },
          IsOwn: { hash: 0x1b619fda, type: DataType.Bool },
          State: { hash: 0xb4afedd3, type: DataType.Enum, options: OWNERSHIP },
        },
        EatSmell: {
          IsChecked: { hash: 0x6c2116e5, type: DataType.Bool },
          IsOwn: { hash: 0x0b6d194c, type: DataType.Bool },
          State: { hash: 0x99e986ab, type: DataType.Enum, options: OWNERSHIP },
        },
        EatWild: {
          IsChecked: { hash: 0x73da071f, type: DataType.Bool },
          IsOwn: { hash: 0x300168bb, type: DataType.Bool },
          State: { hash: 0x1cace476, type: DataType.Enum, options: OWNERSHIP },
        },
        ExpressionLess: {
          IsChecked: { hash: 0x810134b7, type: DataType.Bool },
          IsOwn: { hash: 0x49f8bc37, type: DataType.Bool },
          State: { hash: 0x73444b8a, type: DataType.Enum, options: OWNERSHIP },
        },
        FaceBliss: {
          IsChecked: { hash: 0x2ec44983, type: DataType.Bool },
          IsOwn: { hash: 0x73a7c2ae, type: DataType.Bool },
          State: { hash: 0x9ce00072, type: DataType.Enum, options: OWNERSHIP },
        },
        FaceCloseEyes: {
          IsChecked: { hash: 0x55fc2a2e, type: DataType.Bool },
          IsOwn: { hash: 0x880d469f, type: DataType.Bool },
          State: { hash: 0xbd33319b, type: DataType.Enum, options: OWNERSHIP },
        },
        FaceLousy: {
          IsChecked: { hash: 0xc796d020, type: DataType.Bool },
          IsOwn: { hash: 0x8a5ad390, type: DataType.Bool },
          State: { hash: 0xdf63ccef, type: DataType.Enum, options: OWNERSHIP },
        },
        FaceOpenEyes: {
          IsChecked: { hash: 0x7c241986, type: DataType.Bool },
          IsOwn: { hash: 0xc544f3b2, type: DataType.Bool },
          State: { hash: 0x5a2753a2, type: DataType.Enum, options: OWNERSHIP },
        },
        FaceRaiseEyebrows: {
          IsChecked: { hash: 0x3bc3a386, type: DataType.Bool },
          IsOwn: { hash: 0x4163cddb, type: DataType.Bool },
          State: { hash: 0x7e29eb0b, type: DataType.Enum, options: OWNERSHIP },
        },
        FaceSmile: {
          IsChecked: { hash: 0x61b9a484, type: DataType.Bool },
          IsOwn: { hash: 0x134a22de, type: DataType.Bool },
          State: { hash: 0xbdc755b7, type: DataType.Enum, options: OWNERSHIP },
        },
        FaceSmug: {
          IsChecked: { hash: 0xfdbab391, type: DataType.Bool },
          IsOwn: { hash: 0x10c1c141, type: DataType.Bool },
          State: { hash: 0xa157b401, type: DataType.Enum, options: OWNERSHIP },
        },
        FaceWink: {
          IsChecked: { hash: 0x5e89d26e, type: DataType.Bool },
          IsOwn: { hash: 0x85a2fbaf, type: DataType.Bool },
          State: { hash: 0x7506d07b, type: DataType.Enum, options: OWNERSHIP },
        },
        GetAngryTypeBrightly: {
          IsChecked: { hash: 0xadde61e0, type: DataType.Bool },
          IsOwn: { hash: 0xe86b1a7c, type: DataType.Bool },
          State: { hash: 0xa9d45cc4, type: DataType.Enum, options: OWNERSHIP },
        },
        GetAngryTypeHard: {
          IsChecked: { hash: 0xf5994578, type: DataType.Bool },
          IsOwn: { hash: 0x4e802c75, type: DataType.Bool },
          State: { hash: 0xdc73aa8f, type: DataType.Enum, options: OWNERSHIP },
        },
        GetAngryTypeRegretfulTears: {
          IsChecked: { hash: 0xc30b0466, type: DataType.Bool },
          IsOwn: { hash: 0xe9adf175, type: DataType.Bool },
          State: { hash: 0xb502a407, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingAnnoying: {
          IsChecked: { hash: 0x4660e005, type: DataType.Bool },
          IsOwn: { hash: 0x4ada960a, type: DataType.Bool },
          State: { hash: 0x6dd0d1d3, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingBow: {
          IsChecked: { hash: 0x010854b0, type: DataType.Bool },
          IsOwn: { hash: 0x268b5065, type: DataType.Bool },
          State: { hash: 0x7a587523, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingCurtsy: {
          IsChecked: { hash: 0x4d857d1c, type: DataType.Bool },
          IsOwn: { hash: 0xfeb38906, type: DataType.Bool },
          State: { hash: 0x01ac0147, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingHeadOnly: {
          IsChecked: { hash: 0x5f61fbea, type: DataType.Bool },
          IsOwn: { hash: 0x23f5c780, type: DataType.Bool },
          State: { hash: 0x84ab773b, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingLazy: {
          IsChecked: { hash: 0xa62fe2b2, type: DataType.Bool },
          IsOwn: { hash: 0xda3f5814, type: DataType.Bool },
          State: { hash: 0xdf37929c, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingMacho: {
          IsChecked: { hash: 0x8649dbea, type: DataType.Bool },
          IsOwn: { hash: 0xbcd73fc3, type: DataType.Bool },
          State: { hash: 0xe50f80c0, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingNoble: {
          IsChecked: { hash: 0x367ba340, type: DataType.Bool },
          IsOwn: { hash: 0x3aecc1d6, type: DataType.Bool },
          State: { hash: 0xf2240e32, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingOsu: {
          IsChecked: { hash: 0x4b748a84, type: DataType.Bool },
          IsOwn: { hash: 0xff65dcac, type: DataType.Bool },
          State: { hash: 0xa6bb656f, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingShy: {
          IsChecked: { hash: 0x25e05856, type: DataType.Bool },
          IsOwn: { hash: 0x55850cab, type: DataType.Bool },
          State: { hash: 0xa8b606e6, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingTypeBig: {
          IsChecked: { hash: 0xb9b1ed1f, type: DataType.Bool },
          IsOwn: { hash: 0x5440e20f, type: DataType.Bool },
          State: { hash: 0xb5ab9c92, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingTypeCackle: {
          IsChecked: { hash: 0x673a0aa8, type: DataType.Bool },
          IsOwn: { hash: 0x3194aa4c, type: DataType.Bool },
          State: { hash: 0xcbda3b68, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingTypeNoting: {
          IsChecked: { hash: 0xa77ac939, type: DataType.Bool },
          IsOwn: { hash: 0xbe5f3835, type: DataType.Bool },
          State: { hash: 0x1a33480f, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingTypeShallow: {
          IsChecked: { hash: 0x368fec63, type: DataType.Bool },
          IsOwn: { hash: 0x94f5e658, type: DataType.Bool },
          State: { hash: 0x983ba041, type: DataType.Enum, options: OWNERSHIP },
        },
        GreetingVitality: {
          IsChecked: { hash: 0x77ba0c4e, type: DataType.Bool },
          IsOwn: { hash: 0x10dd63c3, type: DataType.Bool },
          State: { hash: 0x68d9ae98, type: DataType.Enum, options: OWNERSHIP },
        },
        LifeTimeNightOwl: {
          IsChecked: { hash: 0x3084de63, type: DataType.Bool },
          IsOwn: { hash: 0x7ef4fcad, type: DataType.Bool },
          State: { hash: 0x1b56b0a7, type: DataType.Enum, options: OWNERSHIP },
        },
        OftenCrossArms: {
          IsChecked: { hash: 0xcff5f935, type: DataType.Bool },
          IsOwn: { hash: 0x68a04bf7, type: DataType.Bool },
          State: { hash: 0xa0bd4c3e, type: DataType.Enum, options: OWNERSHIP },
        },
        SnoreLoudly: {
          IsChecked: { hash: 0x443675fa, type: DataType.Bool },
          IsOwn: { hash: 0x80311eb5, type: DataType.Bool },
          State: { hash: 0x4df5baef, type: DataType.Enum, options: OWNERSHIP },
        },
        StandAffected: {
          IsChecked: { hash: 0xa259f63a, type: DataType.Bool },
          IsOwn: { hash: 0x6d7cb60c, type: DataType.Bool },
          State: { hash: 0xffc71f21, type: DataType.Enum, options: OWNERSHIP },
        },
        StandCute: {
          IsChecked: { hash: 0x5ee48d0d, type: DataType.Bool },
          IsOwn: { hash: 0xdb45dafc, type: DataType.Bool },
          State: { hash: 0xaef677bb, type: DataType.Enum, options: OWNERSHIP },
        },
        StandHandsFront: {
          IsChecked: { hash: 0x50842fc3, type: DataType.Bool },
          IsOwn: { hash: 0x0db5e8c8, type: DataType.Bool },
          State: { hash: 0xc48e1f04, type: DataType.Enum, options: OWNERSHIP },
        },
        StandLeanForward: {
          IsChecked: { hash: 0x3a3b92e7, type: DataType.Bool },
          IsOwn: { hash: 0x357069c6, type: DataType.Bool },
          State: { hash: 0x31879e64, type: DataType.Enum, options: OWNERSHIP },
        },
        StandProudly: {
          IsChecked: { hash: 0xef014050, type: DataType.Bool },
          IsOwn: { hash: 0x5107123d, type: DataType.Bool },
          State: { hash: 0x0335d7ca, type: DataType.Enum, options: OWNERSHIP },
        },
        StandPutsGlasses: {
          IsChecked: { hash: 0x7e702055, type: DataType.Bool },
          IsOwn: { hash: 0x03956998, type: DataType.Bool },
          State: { hash: 0xec3b9abd, type: DataType.Enum, options: OWNERSHIP },
        },
        StandRestless: {
          IsChecked: { hash: 0xbfed389c, type: DataType.Bool },
          IsOwn: { hash: 0xcbc0be22, type: DataType.Bool },
          State: { hash: 0x12154e45, type: DataType.Enum, options: OWNERSHIP },
        },
        StandRhythm: {
          IsChecked: { hash: 0x06b56546, type: DataType.Bool },
          IsOwn: { hash: 0x8a9067cb, type: DataType.Bool },
          State: { hash: 0x9d079e61, type: DataType.Enum, options: OWNERSHIP },
        },
        StandShakeHip: {
          IsChecked: { hash: 0xa4077361, type: DataType.Bool },
          IsOwn: { hash: 0xb4cb5645, type: DataType.Bool },
          State: { hash: 0x46abd6c1, type: DataType.Enum, options: OWNERSHIP },
        },
        StandShy: {
          IsChecked: { hash: 0xc7e61451, type: DataType.Bool },
          IsOwn: { hash: 0x82466784, type: DataType.Bool },
          State: { hash: 0x738b916a, type: DataType.Enum, options: OWNERSHIP },
        },
        StandStraight: {
          IsChecked: { hash: 0xbc720bab, type: DataType.Bool },
          IsOwn: { hash: 0x0d495f31, type: DataType.Bool },
          State: { hash: 0x27505f15, type: DataType.Enum, options: OWNERSHIP },
        },
        StandSweatLot: {
          IsChecked: { hash: 0x9f6bbb33, type: DataType.Bool },
          IsOwn: { hash: 0x4bdf4cb6, type: DataType.Bool },
          State: { hash: 0x6d949baf, type: DataType.Enum, options: OWNERSHIP },
        },
        StandToeOut: {
          IsChecked: { hash: 0x7c8e1911, type: DataType.Bool },
          IsOwn: { hash: 0xbc7e6b76, type: DataType.Bool },
          State: { hash: 0x32af7d66, type: DataType.Enum, options: OWNERSHIP },
        },
        StomachBig: {
          IsChecked: { hash: 0x9402745e, type: DataType.Bool },
          IsOwn: { hash: 0x3a84f39b, type: DataType.Bool },
          State: { hash: 0x8cec8cd2, type: DataType.Enum, options: OWNERSHIP },
        },
        StomachSmall: {
          IsChecked: { hash: 0x34720e3a, type: DataType.Bool },
          IsOwn: { hash: 0x9e3aac10, type: DataType.Bool },
          State: { hash: 0x83500478, type: DataType.Enum, options: OWNERSHIP },
        },
        TakeItOutOnObject: {
          IsChecked: { hash: 0x5d8feae0, type: DataType.Bool },
          IsOwn: { hash: 0xe4225484, type: DataType.Bool },
          State: { hash: 0x15d9cf75, type: DataType.Enum, options: OWNERSHIP },
        },
        UntidySleeper: {
          IsChecked: { hash: 0xc9a48e18, type: DataType.Bool },
          IsOwn: { hash: 0xd7738b7a, type: DataType.Bool },
          State: { hash: 0xc2402eab, type: DataType.Enum, options: OWNERSHIP },
        },
        VoiceGloomy: {
          IsChecked: { hash: 0x86422d26, type: DataType.Bool },
          IsOwn: { hash: 0x68d9eca6, type: DataType.Bool },
          State: { hash: 0x678944a0, type: DataType.Enum, options: OWNERSHIP },
        },
        VoiceLoud: {
          IsChecked: { hash: 0x72ee4b4e, type: DataType.Bool },
          IsOwn: { hash: 0x0476feea, type: DataType.Bool },
          State: { hash: 0xae00615a, type: DataType.Enum, options: OWNERSHIP },
        },
        VoiceShiny: {
          IsChecked: { hash: 0x59c75c35, type: DataType.Bool },
          IsOwn: { hash: 0xaf2ebc20, type: DataType.Bool },
          State: { hash: 0x2bca4fb9, type: DataType.Enum, options: OWNERSHIP },
        },
        VoiceSmall: {
          IsChecked: { hash: 0x33f5343b, type: DataType.Bool },
          IsOwn: { hash: 0x5bc99ff7, type: DataType.Bool },
          State: { hash: 0xcda310c1, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkFloat: {
          IsChecked: { hash: 0xf171d097, type: DataType.Bool },
          IsOwn: { hash: 0x3c9b11d3, type: DataType.Bool },
          State: { hash: 0xa1a6543a, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkLikeModel: {
          IsChecked: { hash: 0xb2c88407, type: DataType.Bool },
          IsOwn: { hash: 0x5a16d2d4, type: DataType.Bool },
          State: { hash: 0x56d9de05, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkLikeRobot: {
          IsChecked: { hash: 0x55828bbd, type: DataType.Bool },
          IsOwn: { hash: 0xfdd4e509, type: DataType.Bool },
          State: { hash: 0xb51549e7, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkNoSwinging: {
          IsChecked: { hash: 0x11889011, type: DataType.Bool },
          IsOwn: { hash: 0x1dc1140b, type: DataType.Bool },
          State: { hash: 0x95cfe27b, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkRhythm: {
          IsChecked: { hash: 0x0d05fa73, type: DataType.Bool },
          IsOwn: { hash: 0xe0ec9a12, type: DataType.Bool },
          State: { hash: 0xa6811395, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkScurry: {
          IsChecked: { hash: 0xc79936a9, type: DataType.Bool },
          IsOwn: { hash: 0xd36d566d, type: DataType.Bool },
          State: { hash: 0xa95864dd, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkStoop: {
          IsChecked: { hash: 0x2796b8ec, type: DataType.Bool },
          IsOwn: { hash: 0xe9439689, type: DataType.Bool },
          State: { hash: 0x026ca080, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkSwagger: {
          IsChecked: { hash: 0xd3bf8a29, type: DataType.Bool },
          IsOwn: { hash: 0x0b93b046, type: DataType.Bool },
          State: { hash: 0xb5014cee, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkToeIn: {
          IsChecked: { hash: 0x6966926f, type: DataType.Bool },
          IsOwn: { hash: 0xacf38552, type: DataType.Bool },
          State: { hash: 0x40ebf38c, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkToeOut: {
          IsChecked: { hash: 0x06a00044, type: DataType.Bool },
          IsOwn: { hash: 0x3fd459ca, type: DataType.Bool },
          State: { hash: 0x4469e0c0, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkUneasily: {
          IsChecked: { hash: 0xe834b500, type: DataType.Bool },
          IsOwn: { hash: 0xf137a2e6, type: DataType.Bool },
          State: { hash: 0x5babd65e, type: DataType.Enum, options: OWNERSHIP },
        },
        WalkUnsteady: {
          IsChecked: { hash: 0xdc5d91bc, type: DataType.Bool },
          IsOwn: { hash: 0xc5058b30, type: DataType.Bool },
          State: { hash: 0x74b2a44c, type: DataType.Enum, options: OWNERSHIP },
        },
      },
      IsFacePaintFront: { hash: 0x0478516d, type: DataType.Bool },
      Name: {
        FirstPerson: { hash: 0x71b9cc57, type: DataType.WString32 },
        FirstPersonPresetIndex: { hash: 0x1d782567, type: DataType.Int },
        FirstPersonRegionLanguageID: { hash: 0x91d82502, type: DataType.Enum, options: LANGUAGE },
        HowToCallFirstPerson: { hash: 0x810156f2, type: DataType.WString64 },
        HowToCallName: { hash: 0xda1d1acc, type: DataType.WString64 },
        Name: { hash: 0x8b928fa6, type: DataType.WString32 },
        NameRegionLanguageID: { hash: 0xaf18a506, type: DataType.Enum, options: LANGUAGE },
        PronounType: { hash: 0x9f7351a8, type: DataType.Enum, options: PRONOUN },
      },
      NextTime: { hash: 0xd17c7bb4, type: DataType.UInt64 },
      ParentMiiIndex: { hash: 0xe6644dc4, type: DataType.IntArray },
      Voice: {
        Formant: { hash: 0x03577db2, type: DataType.Int },
        Intonation: { hash: 0x3c43b06f, type: DataType.Int },
        Pitch: { hash: 0xede60a39, type: DataType.Int },
        PresetType: { hash: 0xb369aa6b, type: DataType.Enum, options: VOICE_PRESET },
        Speed: { hash: 0x7da2b0aa, type: DataType.Int },
        Tension: { hash: 0x3e31ca7a, type: DataType.Int },
      },
      WordInfo: {
        WordArray: {
          WordHowToCall: { hash: 0xa2eacb08, type: DataType.WString64Array },
          WordKind: { hash: 0x04ceb0b4, type: DataType.EnumArray, options: WORD_KIND },
          WordRegionLanguageID: { hash: 0xc0994b9f, type: DataType.EnumArray, options: LANGUAGE },
          WordText: { hash: 0xb98a5545, type: DataType.WString64Array },
        },
      },
    },
    Reserve: {
      BirthTime: { hash: 0x0f96c18a, type: DataType.UInt64 },
      ParentMiiIndex: { hash: 0xac6f0d0e, type: DataType.IntArray },
    },
    Setting: {
      IsEnableChildbirth: { hash: 0x1a8cd0db, type: DataType.Bool },
    },
  },
  Mii: {
    $self: { hash: 0x5917a80c, type: DataType.Bool64bitKey },
    Belongings: {
      ClothOwnInfo: { hash: 0x84824827, type: DataType.UIntArray },
      CoordinateOwnInfo: { hash: 0x89ce9150, type: DataType.UIntArray },
      ExteriorNextEmotionBallTime: { hash: 0xf580d0f4, type: DataType.UInt64Array },
      GoodsOwnInfoSlot: {
        GetTime: { hash: 0x48c3881a, type: DataType.UInt64Array },
        GoodsStringId: { hash: 0xe3d6005e, type: DataType.UIntArray },
        UgcGoodsIndex: { hash: 0x2115afb6, type: DataType.IntArray },
      },
      HabitOwnInfo: {
        BlinkLot: {
          IsChecked: { hash: 0x43c41d5b, type: DataType.BoolArray },
          IsOwn: { hash: 0x8983d387, type: DataType.BoolArray },
          State: { hash: 0x3e182162, type: DataType.EnumArray, options: OWNERSHIP },
        },
        BreakGas: {
          IsChecked: { hash: 0x20cceece, type: DataType.BoolArray },
          IsOwn: { hash: 0xbbe78775, type: DataType.BoolArray },
          State: { hash: 0x13de36b3, type: DataType.EnumArray, options: OWNERSHIP },
        },
        ChangeCloth: {
          IsChecked: { hash: 0xd63c1381, type: DataType.BoolArray },
          IsOwn: { hash: 0x66e29006, type: DataType.BoolArray },
          State: { hash: 0x3ae4050e, type: DataType.EnumArray, options: OWNERSHIP },
        },
        Chicken: {
          IsChecked: { hash: 0x5c89d8be, type: DataType.BoolArray },
          IsOwn: { hash: 0x4f90bd07, type: DataType.BoolArray },
          State: { hash: 0xb8228ab9, type: DataType.EnumArray, options: OWNERSHIP },
        },
        EatCarefully: {
          IsChecked: { hash: 0xc3f4ddbc, type: DataType.BoolArray },
          IsOwn: { hash: 0xd7552023, type: DataType.BoolArray },
          State: { hash: 0x5100bcc0, type: DataType.EnumArray, options: OWNERSHIP },
        },
        EatCrisp: {
          IsChecked: { hash: 0x0c7bf8a1, type: DataType.BoolArray },
          IsOwn: { hash: 0xdb450022, type: DataType.BoolArray },
          State: { hash: 0xbc5a7541, type: DataType.EnumArray, options: OWNERSHIP },
        },
        EatCute: {
          IsChecked: { hash: 0x49fa3488, type: DataType.BoolArray },
          IsOwn: { hash: 0x9de169d5, type: DataType.BoolArray },
          State: { hash: 0x61bdd48f, type: DataType.EnumArray, options: OWNERSHIP },
        },
        EatElegantly: {
          IsChecked: { hash: 0x46174393, type: DataType.BoolArray },
          IsOwn: { hash: 0xf038d194, type: DataType.BoolArray },
          State: { hash: 0x5996017f, type: DataType.EnumArray, options: OWNERSHIP },
        },
        EatMouthful: {
          IsChecked: { hash: 0xb14be88f, type: DataType.BoolArray },
          IsOwn: { hash: 0x24957221, type: DataType.BoolArray },
          State: { hash: 0x36d3a6a0, type: DataType.EnumArray, options: OWNERSHIP },
        },
        EatSecretly: {
          IsChecked: { hash: 0xc09c0386, type: DataType.BoolArray },
          IsOwn: { hash: 0x1f7f63ab, type: DataType.BoolArray },
          State: { hash: 0xa2d9c3ba, type: DataType.EnumArray, options: OWNERSHIP },
        },
        EatSmell: {
          IsChecked: { hash: 0xb33f0f1c, type: DataType.BoolArray },
          IsOwn: { hash: 0x017afebb, type: DataType.BoolArray },
          State: { hash: 0x91d0b7c6, type: DataType.EnumArray, options: OWNERSHIP },
        },
        EatWild: {
          IsChecked: { hash: 0x0b95831e, type: DataType.BoolArray },
          IsOwn: { hash: 0x9f73e5c9, type: DataType.BoolArray },
          State: { hash: 0x5ec85faa, type: DataType.EnumArray, options: OWNERSHIP },
        },
        ExpressionLess: {
          IsChecked: { hash: 0xbd3a2655, type: DataType.BoolArray },
          IsOwn: { hash: 0x3c7ed87d, type: DataType.BoolArray },
          State: { hash: 0xd6661108, type: DataType.EnumArray, options: OWNERSHIP },
        },
        FaceBliss: {
          IsChecked: { hash: 0x59cc7a99, type: DataType.BoolArray },
          IsOwn: { hash: 0x9303258e, type: DataType.BoolArray },
          State: { hash: 0x2df14f78, type: DataType.EnumArray, options: OWNERSHIP },
        },
        FaceCloseEyes: {
          IsChecked: { hash: 0x31697a11, type: DataType.BoolArray },
          IsOwn: { hash: 0x0fa98d6f, type: DataType.BoolArray },
          State: { hash: 0xe8ac5272, type: DataType.EnumArray, options: OWNERSHIP },
        },
        FaceLousy: {
          IsChecked: { hash: 0x127bfb12, type: DataType.BoolArray },
          IsOwn: { hash: 0x93d996da, type: DataType.BoolArray },
          State: { hash: 0x45709d00, type: DataType.EnumArray, options: OWNERSHIP },
        },
        FaceOpenEyes: {
          IsChecked: { hash: 0xf3b92c68, type: DataType.BoolArray },
          IsOwn: { hash: 0xf33cb427, type: DataType.BoolArray },
          State: { hash: 0x13364a8b, type: DataType.EnumArray, options: OWNERSHIP },
        },
        FaceRaiseEyebrows: {
          IsChecked: { hash: 0x102d6f60, type: DataType.BoolArray },
          IsOwn: { hash: 0x78f22336, type: DataType.BoolArray },
          State: { hash: 0x6c993313, type: DataType.EnumArray, options: OWNERSHIP },
        },
        FaceSmile: {
          IsChecked: { hash: 0xcd07c437, type: DataType.BoolArray },
          IsOwn: { hash: 0x3d315969, type: DataType.BoolArray },
          State: { hash: 0x628f34c7, type: DataType.EnumArray, options: OWNERSHIP },
        },
        FaceSmug: {
          IsChecked: { hash: 0x0eefe1b6, type: DataType.BoolArray },
          IsOwn: { hash: 0xed2e0ad9, type: DataType.BoolArray },
          State: { hash: 0xa8e0e412, type: DataType.EnumArray, options: OWNERSHIP },
        },
        FaceWink: {
          IsChecked: { hash: 0x52ad16fe, type: DataType.BoolArray },
          IsOwn: { hash: 0xa1a80a03, type: DataType.BoolArray },
          State: { hash: 0x425aba8a, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GetAngryTypeBrightly: {
          IsChecked: { hash: 0xca60869a, type: DataType.BoolArray },
          IsOwn: { hash: 0x1f3e6114, type: DataType.BoolArray },
          State: { hash: 0x0a9e68d5, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GetAngryTypeHard: {
          IsChecked: { hash: 0x3025f187, type: DataType.BoolArray },
          IsOwn: { hash: 0x83a7521f, type: DataType.BoolArray },
          State: { hash: 0x8d7cbae6, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GetAngryTypeRegretfulTears: {
          IsChecked: { hash: 0x449d3fc8, type: DataType.BoolArray },
          IsOwn: { hash: 0xb1880ee3, type: DataType.BoolArray },
          State: { hash: 0x9c93aed1, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingAnnoying: {
          IsChecked: { hash: 0x26ce4771, type: DataType.BoolArray },
          IsOwn: { hash: 0xa0bd10d3, type: DataType.BoolArray },
          State: { hash: 0xc3403519, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingBow: {
          IsChecked: { hash: 0x7e4b1843, type: DataType.BoolArray },
          IsOwn: { hash: 0x74144f05, type: DataType.BoolArray },
          State: { hash: 0xc68bd363, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingCurtsy: {
          IsChecked: { hash: 0x8abf504a, type: DataType.BoolArray },
          IsOwn: { hash: 0xd4bc72f0, type: DataType.BoolArray },
          State: { hash: 0x8e8a0d2a, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingHeadOnly: {
          IsChecked: { hash: 0xb9151480, type: DataType.BoolArray },
          IsOwn: { hash: 0x6f51ccfb, type: DataType.BoolArray },
          State: { hash: 0xca357d5f, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingLazy: {
          IsChecked: { hash: 0xa2782478, type: DataType.BoolArray },
          IsOwn: { hash: 0x87f60bcd, type: DataType.BoolArray },
          State: { hash: 0xf18d542c, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingMacho: {
          IsChecked: { hash: 0x5ab6b817, type: DataType.BoolArray },
          IsOwn: { hash: 0x239465b8, type: DataType.BoolArray },
          State: { hash: 0xbd23a855, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingNoble: {
          IsChecked: { hash: 0x2677176d, type: DataType.BoolArray },
          IsOwn: { hash: 0xb82ec29e, type: DataType.BoolArray },
          State: { hash: 0xf766a6be, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingOsu: {
          IsChecked: { hash: 0x39933d74, type: DataType.BoolArray },
          IsOwn: { hash: 0x76cd4d85, type: DataType.BoolArray },
          State: { hash: 0x7d3608fb, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingShy: {
          IsChecked: { hash: 0x30c02b53, type: DataType.BoolArray },
          IsOwn: { hash: 0xae959ab7, type: DataType.BoolArray },
          State: { hash: 0x938a18f7, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingTypeBig: {
          IsChecked: { hash: 0xca8146ab, type: DataType.BoolArray },
          IsOwn: { hash: 0x1e838480, type: DataType.BoolArray },
          State: { hash: 0x7219f50e, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingTypeCackle: {
          IsChecked: { hash: 0x91c60d48, type: DataType.BoolArray },
          IsOwn: { hash: 0x465b6fae, type: DataType.BoolArray },
          State: { hash: 0xaa099f58, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingTypeNoting: {
          IsChecked: { hash: 0x8803d8ec, type: DataType.BoolArray },
          IsOwn: { hash: 0x60299d3b, type: DataType.BoolArray },
          State: { hash: 0xbe2a255e, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingTypeShallow: {
          IsChecked: { hash: 0xb23f2bb5, type: DataType.BoolArray },
          IsOwn: { hash: 0xb216e22b, type: DataType.BoolArray },
          State: { hash: 0x6b834fa2, type: DataType.EnumArray, options: OWNERSHIP },
        },
        GreetingVitality: {
          IsChecked: { hash: 0x218f31bf, type: DataType.BoolArray },
          IsOwn: { hash: 0x14fd3571, type: DataType.BoolArray },
          State: { hash: 0xb7fec40f, type: DataType.EnumArray, options: OWNERSHIP },
        },
        LifeTimeNightOwl: {
          IsChecked: { hash: 0x50d44d5f, type: DataType.BoolArray },
          IsOwn: { hash: 0x909b6360, type: DataType.BoolArray },
          State: { hash: 0x5aea0fa6, type: DataType.EnumArray, options: OWNERSHIP },
        },
        OftenCrossArms: {
          IsChecked: { hash: 0x9f035a23, type: DataType.BoolArray },
          IsOwn: { hash: 0xd53b457f, type: DataType.BoolArray },
          State: { hash: 0x9be46b74, type: DataType.EnumArray, options: OWNERSHIP },
        },
        SnoreLoudly: {
          IsChecked: { hash: 0xee26b823, type: DataType.BoolArray },
          IsOwn: { hash: 0xebeb53ba, type: DataType.BoolArray },
          State: { hash: 0x5ad99f10, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandAffected: {
          IsChecked: { hash: 0x61ab172c, type: DataType.BoolArray },
          IsOwn: { hash: 0x4d9e59b0, type: DataType.BoolArray },
          State: { hash: 0x2a073b9d, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandCute: {
          IsChecked: { hash: 0x8ec8bd02, type: DataType.BoolArray },
          IsOwn: { hash: 0x238e7641, type: DataType.BoolArray },
          State: { hash: 0x9d72ecb6, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandHandsFront: {
          IsChecked: { hash: 0xbdfa8171, type: DataType.BoolArray },
          IsOwn: { hash: 0xb36614ee, type: DataType.BoolArray },
          State: { hash: 0x2813925d, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandLeanForward: {
          IsChecked: { hash: 0x654c2de0, type: DataType.BoolArray },
          IsOwn: { hash: 0x0a9b75d1, type: DataType.BoolArray },
          State: { hash: 0x7097829c, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandProudly: {
          IsChecked: { hash: 0x285db625, type: DataType.BoolArray },
          IsOwn: { hash: 0xc7b1fa2c, type: DataType.BoolArray },
          State: { hash: 0x17392ebc, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandPutsGlasses: {
          IsChecked: { hash: 0x0826a5da, type: DataType.BoolArray },
          IsOwn: { hash: 0x2efcd1cb, type: DataType.BoolArray },
          State: { hash: 0x0e0dd235, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandRestless: {
          IsChecked: { hash: 0xb392b5b7, type: DataType.BoolArray },
          IsOwn: { hash: 0xd21bc79a, type: DataType.BoolArray },
          State: { hash: 0x025fe88d, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandRhythm: {
          IsChecked: { hash: 0xdac89a9a, type: DataType.BoolArray },
          IsOwn: { hash: 0x78a38519, type: DataType.BoolArray },
          State: { hash: 0xae933f06, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandShakeHip: {
          IsChecked: { hash: 0x852dcd33, type: DataType.BoolArray },
          IsOwn: { hash: 0xd6259cf5, type: DataType.BoolArray },
          State: { hash: 0x342650e9, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandShy: {
          IsChecked: { hash: 0xa40cc150, type: DataType.BoolArray },
          IsOwn: { hash: 0xf0226fc2, type: DataType.BoolArray },
          State: { hash: 0x099dc029, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandStraight: {
          IsChecked: { hash: 0x5ddc98f3, type: DataType.BoolArray },
          IsOwn: { hash: 0xd9912574, type: DataType.BoolArray },
          State: { hash: 0x47122bc4, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandSweatLot: {
          IsChecked: { hash: 0x29eedc59, type: DataType.BoolArray },
          IsOwn: { hash: 0xd6aaa58f, type: DataType.BoolArray },
          State: { hash: 0x4437585f, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StandToeOut: {
          IsChecked: { hash: 0x8da9a92c, type: DataType.BoolArray },
          IsOwn: { hash: 0x1144d3f4, type: DataType.BoolArray },
          State: { hash: 0x83fc68b2, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StomachBig: {
          IsChecked: { hash: 0x16905849, type: DataType.BoolArray },
          IsOwn: { hash: 0x0f695e07, type: DataType.BoolArray },
          State: { hash: 0x93398818, type: DataType.EnumArray, options: OWNERSHIP },
        },
        StomachSmall: {
          IsChecked: { hash: 0xfe52e05f, type: DataType.BoolArray },
          IsOwn: { hash: 0x9def16d9, type: DataType.BoolArray },
          State: { hash: 0xbdcf6a0a, type: DataType.EnumArray, options: OWNERSHIP },
        },
        TakeItOutOnObject: {
          IsChecked: { hash: 0x07deee9a, type: DataType.BoolArray },
          IsOwn: { hash: 0x18fbaa2f, type: DataType.BoolArray },
          State: { hash: 0x6e728262, type: DataType.EnumArray, options: OWNERSHIP },
        },
        UntidySleeper: {
          IsChecked: { hash: 0xf7f39acd, type: DataType.BoolArray },
          IsOwn: { hash: 0x646e94f3, type: DataType.BoolArray },
          State: { hash: 0x92154914, type: DataType.EnumArray, options: OWNERSHIP },
        },
        VoiceGloomy: {
          IsChecked: { hash: 0x92e2cdba, type: DataType.BoolArray },
          IsOwn: { hash: 0x2932cd0e, type: DataType.BoolArray },
          State: { hash: 0x1bd5857e, type: DataType.EnumArray, options: OWNERSHIP },
        },
        VoiceLoud: {
          IsChecked: { hash: 0x6244f6d7, type: DataType.BoolArray },
          IsOwn: { hash: 0x80cfac69, type: DataType.BoolArray },
          State: { hash: 0xaa81c246, type: DataType.EnumArray, options: OWNERSHIP },
        },
        VoiceShiny: {
          IsChecked: { hash: 0xa1e2abaa, type: DataType.BoolArray },
          IsOwn: { hash: 0xd97d035e, type: DataType.BoolArray },
          State: { hash: 0xf4758f7e, type: DataType.EnumArray, options: OWNERSHIP },
        },
        VoiceSmall: {
          IsChecked: { hash: 0xa985909d, type: DataType.BoolArray },
          IsOwn: { hash: 0xbb27de15, type: DataType.BoolArray },
          State: { hash: 0x74b76c8a, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkFloat: {
          IsChecked: { hash: 0x783e075c, type: DataType.BoolArray },
          IsOwn: { hash: 0xeea928a3, type: DataType.BoolArray },
          State: { hash: 0x8eb39b91, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkLikeModel: {
          IsChecked: { hash: 0x92f88586, type: DataType.BoolArray },
          IsOwn: { hash: 0x2e490046, type: DataType.BoolArray },
          State: { hash: 0x8955d254, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkLikeRobot: {
          IsChecked: { hash: 0x5965f2d2, type: DataType.BoolArray },
          IsOwn: { hash: 0xa2cfe425, type: DataType.BoolArray },
          State: { hash: 0x8e56bb7f, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkNoSwinging: {
          IsChecked: { hash: 0x54a53b03, type: DataType.BoolArray },
          IsOwn: { hash: 0xa12926a3, type: DataType.BoolArray },
          State: { hash: 0x2da48396, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkRhythm: {
          IsChecked: { hash: 0xa4efd875, type: DataType.BoolArray },
          IsOwn: { hash: 0xe807cd6a, type: DataType.BoolArray },
          State: { hash: 0xab8c2a5f, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkScurry: {
          IsChecked: { hash: 0x4d6d3d57, type: DataType.BoolArray },
          IsOwn: { hash: 0x632f8b26, type: DataType.BoolArray },
          State: { hash: 0x052f2396, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkStoop: {
          IsChecked: { hash: 0x9312bce5, type: DataType.BoolArray },
          IsOwn: { hash: 0xa98dee36, type: DataType.BoolArray },
          State: { hash: 0x8b46011d, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkSwagger: {
          IsChecked: { hash: 0xb6d7c3ec, type: DataType.BoolArray },
          IsOwn: { hash: 0x5f2fb745, type: DataType.BoolArray },
          State: { hash: 0xcba8a8fe, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkToeIn: {
          IsChecked: { hash: 0xe5cf6c26, type: DataType.BoolArray },
          IsOwn: { hash: 0x3ffa423f, type: DataType.BoolArray },
          State: { hash: 0x5c2ba98d, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkToeOut: {
          IsChecked: { hash: 0xe296df36, type: DataType.BoolArray },
          IsOwn: { hash: 0x2b638525, type: DataType.BoolArray },
          State: { hash: 0xbe6bb739, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkUneasily: {
          IsChecked: { hash: 0x8ccfe03d, type: DataType.BoolArray },
          IsOwn: { hash: 0x76c8a84c, type: DataType.BoolArray },
          State: { hash: 0xb6f01e78, type: DataType.EnumArray, options: OWNERSHIP },
        },
        WalkUnsteady: {
          IsChecked: { hash: 0xf523a482, type: DataType.BoolArray },
          IsOwn: { hash: 0x444cdfd1, type: DataType.BoolArray },
          State: { hash: 0xde90958f, type: DataType.EnumArray, options: OWNERSHIP },
        },
      },
      InteriorNextEmotionBallTime: { hash: 0x5ca4f5d2, type: DataType.UInt64Array },
      Money: { hash: 0xf334fd2e, type: DataType.UIntArray },
      NextInteriorWantGameTime: { hash: 0x800e786e, type: DataType.UInt64Array },
      RoomStyleInfo: {
        Flag: {
          Abduction00: { hash: 0x032e96c2, type: DataType.BoolArray },
          Antarctic00: { hash: 0x838bb104, type: DataType.BoolArray },
          Asianresort00: { hash: 0x1b306dd7, type: DataType.BoolArray },
          Asianresort01: { hash: 0x6613a246, type: DataType.BoolArray },
          Atelier00: { hash: 0x02648bc7, type: DataType.BoolArray },
          Atelier01: { hash: 0xe6523c59, type: DataType.BoolArray },
          Baby00: { hash: 0xee204684, type: DataType.BoolArray },
          Baby01: { hash: 0x80a4e0f7, type: DataType.BoolArray },
          Baby02: { hash: 0xcc029b0d, type: DataType.BoolArray },
          Bathroom00: { hash: 0xdf531764, type: DataType.BoolArray },
          Bathroom01: { hash: 0x4d1943e1, type: DataType.BoolArray },
          Bathroom02: { hash: 0x43ba3319, type: DataType.BoolArray },
          Bathroom03: { hash: 0x410de7b5, type: DataType.BoolArray },
          Bathroom04: { hash: 0xa0ec0923, type: DataType.BoolArray },
          Beach00: { hash: 0xc65c87c2, type: DataType.BoolArray },
          BigFlower00: { hash: 0xe0788131, type: DataType.BoolArray },
          BigFlower01: { hash: 0xc7b03f5e, type: DataType.BoolArray },
          BigFlower02: { hash: 0x92af6d1e, type: DataType.BoolArray },
          BigFlower03: { hash: 0x1409d901, type: DataType.BoolArray },
          BlueSheet00: { hash: 0xf4ce25e2, type: DataType.BoolArray },
          Book00: { hash: 0xf154c180, type: DataType.BoolArray },
          Book01: { hash: 0x7087026f, type: DataType.BoolArray },
          Book02: { hash: 0x17c7ea50, type: DataType.BoolArray },
          Botanical00: { hash: 0xc516de3d, type: DataType.BoolArray },
          Brick00: { hash: 0x79fddeeb, type: DataType.BoolArray },
          Brick01: { hash: 0x659ce483, type: DataType.BoolArray },
          Cage00: { hash: 0x8345e2f2, type: DataType.BoolArray },
          Camouflage00: { hash: 0x4180007e, type: DataType.BoolArray },
          Camouflage01: { hash: 0x0c878061, type: DataType.BoolArray },
          Camouflage02: { hash: 0x9c3a5ca8, type: DataType.BoolArray },
          Camouflage03: { hash: 0x27ed8c61, type: DataType.BoolArray },
          Candy00: { hash: 0x63bf31ef, type: DataType.BoolArray },
          Candy01: { hash: 0x8e090478, type: DataType.BoolArray },
          Candy02: { hash: 0xa39d8c28, type: DataType.BoolArray },
          Cemetery00: { hash: 0x3ecc78e7, type: DataType.BoolArray },
          Chinese00: { hash: 0x4f587bfc, type: DataType.BoolArray },
          Chinese01: { hash: 0xeecda1f3, type: DataType.BoolArray },
          Christmas00: { hash: 0xf6dca45f, type: DataType.BoolArray },
          Christmas01: { hash: 0x0784c30f, type: DataType.BoolArray },
          Classroom00: { hash: 0x4b82e39c, type: DataType.BoolArray },
          Classroom01: { hash: 0x18bcfe49, type: DataType.BoolArray },
          Club00: { hash: 0xaa9db948, type: DataType.BoolArray },
          Cute00: { hash: 0xa76889c2, type: DataType.BoolArray },
          Cute01: { hash: 0xa6762418, type: DataType.BoolArray },
          Damask00: { hash: 0x22b850d0, type: DataType.BoolArray },
          Damask01: { hash: 0x0dc3e2f5, type: DataType.BoolArray },
          Damask02: { hash: 0xc737a2f1, type: DataType.BoolArray },
          Damask03: { hash: 0xe5d9fbb6, type: DataType.BoolArray },
          Damask04: { hash: 0x74fdb353, type: DataType.BoolArray },
          Damask05: { hash: 0x4f8f9bed, type: DataType.BoolArray },
          Damask06: { hash: 0x6dfbfb8c, type: DataType.BoolArray },
          Damask07: { hash: 0xb32d920f, type: DataType.BoolArray },
          Desert00: { hash: 0x8b7037aa, type: DataType.BoolArray },
          Dilapidated00: { hash: 0x55201456, type: DataType.BoolArray },
          Dinosaur00: { hash: 0xbb6c1435, type: DataType.BoolArray },
          Dinosaur01: { hash: 0x0cd5f1ad, type: DataType.BoolArray },
          Dog00: { hash: 0x38e02ccc, type: DataType.BoolArray },
          Dog01: { hash: 0x8c028a48, type: DataType.BoolArray },
          Dot00: { hash: 0x48f247d4, type: DataType.BoolArray },
          Dot01: { hash: 0xf7f57894, type: DataType.BoolArray },
          Dot02: { hash: 0x648e42f2, type: DataType.BoolArray },
          Dot03: { hash: 0x35effc92, type: DataType.BoolArray },
          Dot04: { hash: 0x8fc94d1c, type: DataType.BoolArray },
          Dot05: { hash: 0x1ebb958c, type: DataType.BoolArray },
          Dot06: { hash: 0x2ddc7ccc, type: DataType.BoolArray },
          Dot07: { hash: 0xf9292527, type: DataType.BoolArray },
          DropCurtain00: { hash: 0xc1aaff9f, type: DataType.BoolArray },
          Factry00: { hash: 0x05585740, type: DataType.BoolArray },
          Fantasy00: { hash: 0xac7e7959, type: DataType.BoolArray },
          Fantasy01: { hash: 0xfa52eee5, type: DataType.BoolArray },
          Fantasy02: { hash: 0xce11bbb8, type: DataType.BoolArray },
          Festival00: { hash: 0xd7f41284, type: DataType.BoolArray },
          Field00: { hash: 0x919d05eb, type: DataType.BoolArray },
          Field01: { hash: 0x529c42eb, type: DataType.BoolArray },
          Flowergarden00: { hash: 0x07fac41d, type: DataType.BoolArray },
          Formula00: { hash: 0xc74470cd, type: DataType.BoolArray },
          Formula01: { hash: 0x8697e70c, type: DataType.BoolArray },
          Fruit00: { hash: 0x8c171da8, type: DataType.BoolArray },
          Fruit01: { hash: 0x15ca1f12, type: DataType.BoolArray },
          Fruit02: { hash: 0x4b3e8d82, type: DataType.BoolArray },
          Fruit03: { hash: 0x7e288636, type: DataType.BoolArray },
          Fruit04: { hash: 0x816fad0e, type: DataType.BoolArray },
          Fruit05: { hash: 0x0be115a9, type: DataType.BoolArray },
          Fruit06: { hash: 0x61f159f6, type: DataType.BoolArray },
          Fruit07: { hash: 0xf41e974d, type: DataType.BoolArray },
          Galaxy00: { hash: 0xaba22660, type: DataType.BoolArray },
          Game00: { hash: 0x54294f71, type: DataType.BoolArray },
          Game01: { hash: 0xd2c6d1d4, type: DataType.BoolArray },
          Garage00: { hash: 0xba131383, type: DataType.BoolArray },
          Garage01: { hash: 0xc72a49ad, type: DataType.BoolArray },
          Garage02: { hash: 0x69d426cc, type: DataType.BoolArray },
          Garage03: { hash: 0x298f8df2, type: DataType.BoolArray },
          Garage04: { hash: 0x0bfbb3d2, type: DataType.BoolArray },
          Garage05: { hash: 0xc2cfb799, type: DataType.BoolArray },
          Garage06: { hash: 0x6a6eaa18, type: DataType.BoolArray },
          Garage07: { hash: 0xcf1afb87, type: DataType.BoolArray },
          Garden00: { hash: 0xe9d8877d, type: DataType.BoolArray },
          GardenWedding00: { hash: 0x4ff2da8f, type: DataType.BoolArray },
          Gold00: { hash: 0x570525c8, type: DataType.BoolArray },
          Grassland00: { hash: 0x820c7299, type: DataType.BoolArray },
          Gym00: { hash: 0xbbf8a4cc, type: DataType.BoolArray },
          Gym01: { hash: 0xa8d8940d, type: DataType.BoolArray },
          Gym02: { hash: 0x4eb5d9fc, type: DataType.BoolArray },
          Halloween00: { hash: 0xa3615a5f, type: DataType.BoolArray },
          Heart00: { hash: 0x6a3f8319, type: DataType.BoolArray },
          Heart01: { hash: 0xc490a19e, type: DataType.BoolArray },
          Heart02: { hash: 0xdef9f1c7, type: DataType.BoolArray },
          Heart03: { hash: 0x8db34deb, type: DataType.BoolArray },
          Heart04: { hash: 0xc89e96f7, type: DataType.BoolArray },
          Heaven00: { hash: 0x34a6b7f5, type: DataType.BoolArray },
          HoneycombTile00: { hash: 0x2b782597, type: DataType.BoolArray },
          HoneycombTile01: { hash: 0xbbe60928, type: DataType.BoolArray },
          HoneycombTile02: { hash: 0x2001aa24, type: DataType.BoolArray },
          HoneycombTile03: { hash: 0xca092458, type: DataType.BoolArray },
          HoneycombTile04: { hash: 0x061beaee, type: DataType.BoolArray },
          Horror00: { hash: 0x49884e1b, type: DataType.BoolArray },
          Horror01: { hash: 0x87e10baf, type: DataType.BoolArray },
          Hospital00: { hash: 0x5b17ce6e, type: DataType.BoolArray },
          IceRink00: { hash: 0x27d82323, type: DataType.BoolArray },
          InterviewBoard00: { hash: 0xfb973a08, type: DataType.BoolArray },
          Jail00: { hash: 0x984c5385, type: DataType.BoolArray },
          Japanese00: { hash: 0xfb6d88fd, type: DataType.BoolArray },
          Japanese01: { hash: 0x203390f0, type: DataType.BoolArray },
          Japanese02: { hash: 0x314a2f52, type: DataType.BoolArray },
          Japanese03: { hash: 0xb02c2270, type: DataType.BoolArray },
          Japanese04: { hash: 0x196fb0df, type: DataType.BoolArray },
          Japanese05: { hash: 0x428a1930, type: DataType.BoolArray },
          Jungle00: { hash: 0x07be0c7a, type: DataType.BoolArray },
          Labo00: { hash: 0x5f5ce49c, type: DataType.BoolArray },
          Lace00: { hash: 0xc5367c5c, type: DataType.BoolArray },
          Lace01: { hash: 0xba015317, type: DataType.BoolArray },
          Lace02: { hash: 0x9b2e0085, type: DataType.BoolArray },
          Lace03: { hash: 0xef086ee0, type: DataType.BoolArray },
          Lace04: { hash: 0xb7f82df5, type: DataType.BoolArray },
          Lace05: { hash: 0x3bb7a31d, type: DataType.BoolArray },
          LightStick00: { hash: 0xf67edb25, type: DataType.BoolArray },
          LightStick01: { hash: 0x01f82546, type: DataType.BoolArray },
          LightStick02: { hash: 0xa5da01ed, type: DataType.BoolArray },
          LightStick03: { hash: 0xc0f85737, type: DataType.BoolArray },
          LightStick04: { hash: 0xa9aad8ef, type: DataType.BoolArray },
          LightStick05: { hash: 0xf96ba314, type: DataType.BoolArray },
          LightStick06: { hash: 0x092c3be2, type: DataType.BoolArray },
          LightStick07: { hash: 0x5703e748, type: DataType.BoolArray },
          LockerRoom00: { hash: 0x8265f26c, type: DataType.BoolArray },
          LockerRoom01: { hash: 0xe76b40f4, type: DataType.BoolArray },
          LockerRoom02: { hash: 0x91e40ebd, type: DataType.BoolArray },
          Log00: { hash: 0xa1aa8bbc, type: DataType.BoolArray },
          Marble00: { hash: 0x0f85a2c2, type: DataType.BoolArray },
          Marble01: { hash: 0x135cc1c2, type: DataType.BoolArray },
          Market00: { hash: 0x889b6892, type: DataType.BoolArray },
          Midcentury00: { hash: 0xc9e2859b, type: DataType.BoolArray },
          Midcentury01: { hash: 0xfc968e25, type: DataType.BoolArray },
          Minimul00: { hash: 0x49a9fe1a, type: DataType.BoolArray },
          Minimul01: { hash: 0xa5cacbf0, type: DataType.BoolArray },
          Minimul02: { hash: 0x7d71b055, type: DataType.BoolArray },
          Minimul03: { hash: 0x8a3cf089, type: DataType.BoolArray },
          Minimul04: { hash: 0xb64bd812, type: DataType.BoolArray },
          Minimul05: { hash: 0xb4c110c5, type: DataType.BoolArray },
          Minimul06: { hash: 0x054c304e, type: DataType.BoolArray },
          Minimul07: { hash: 0xa7abc5c6, type: DataType.BoolArray },
          MonitorRoom00: { hash: 0x1819a593, type: DataType.BoolArray },
          MonitorRoom01: { hash: 0x482d23e4, type: DataType.BoolArray },
          MonitorRoom02: { hash: 0x367eaf87, type: DataType.BoolArray },
          MovingBox00: { hash: 0x174219a8, type: DataType.BoolArray },
          MovingBox01: { hash: 0xdde21baf, type: DataType.BoolArray },
          MultiDot00: { hash: 0xee7a5d14, type: DataType.BoolArray },
          MultiDot01: { hash: 0x219aae6c, type: DataType.BoolArray },
          MultiDot02: { hash: 0x1de8d698, type: DataType.BoolArray },
          MultiDot03: { hash: 0x98b57515, type: DataType.BoolArray },
          MusicRoom00: { hash: 0xb1cce24e, type: DataType.BoolArray },
          NeonSign00: { hash: 0x670e86ca, type: DataType.BoolArray },
          NightView00: { hash: 0x3ce3363c, type: DataType.BoolArray },
          Nobility00: { hash: 0x6db42ced, type: DataType.BoolArray },
          Nobility01: { hash: 0x85a8caee, type: DataType.BoolArray },
          Nobility02: { hash: 0xdd78e508, type: DataType.BoolArray },
          Office00: { hash: 0x082b2678, type: DataType.BoolArray },
          Office01: { hash: 0x0149a3d2, type: DataType.BoolArray },
          Otaku00: { hash: 0xd686fd28, type: DataType.BoolArray },
          Otaku02: { hash: 0x4792f9ca, type: DataType.BoolArray },
          Otaku03: { hash: 0x5332e2a1, type: DataType.BoolArray },
          Otaku04: { hash: 0x49156885, type: DataType.BoolArray },
          Party00: { hash: 0x98d3bf93, type: DataType.BoolArray },
          Party01: { hash: 0x081d943b, type: DataType.BoolArray },
          Party02: { hash: 0x350c9723, type: DataType.BoolArray },
          Party03: { hash: 0x7ae1e9b2, type: DataType.BoolArray },
          Party04: { hash: 0xc923b6b8, type: DataType.BoolArray },
          Party05: { hash: 0x87a4664e, type: DataType.BoolArray },
          Party06: { hash: 0x77b111c0, type: DataType.BoolArray },
          Party07: { hash: 0xf1faa8b7, type: DataType.BoolArray },
          Pirate00: { hash: 0xb1ca0ebc, type: DataType.BoolArray },
          PublicBath00: { hash: 0xd2aa8a5d, type: DataType.BoolArray },
          Rain00: { hash: 0x951c2e6c, type: DataType.BoolArray },
          SF00: { hash: 0x8991500f, type: DataType.BoolArray },
          SF01: { hash: 0xbbf739d5, type: DataType.BoolArray },
          SF02: { hash: 0xffbdfac5, type: DataType.BoolArray },
          SF03: { hash: 0xbf48bc95, type: DataType.BoolArray },
          SF04: { hash: 0x1b148eef, type: DataType.BoolArray },
          SF05: { hash: 0xcca1a303, type: DataType.BoolArray },
          SFX00: { hash: 0x86f0e25c, type: DataType.BoolArray },
          SFX01: { hash: 0x484907d1, type: DataType.BoolArray },
          Sakura00: { hash: 0x9e27a29b, type: DataType.BoolArray },
          Sauna00: { hash: 0x43e33b98, type: DataType.BoolArray },
          Shogun00: { hash: 0x3656669d, type: DataType.BoolArray },
          Shoji00: { hash: 0xca08a5b7, type: DataType.BoolArray },
          Shoji01: { hash: 0xd679c77f, type: DataType.BoolArray },
          Shoji02: { hash: 0x382d9dab, type: DataType.BoolArray },
          Simple00: { hash: 0x29516b5b, type: DataType.BoolArray },
          Sloppy00: { hash: 0xba2c4bed, type: DataType.BoolArray },
          Sloppy01: { hash: 0x0b0c8a54, type: DataType.BoolArray },
          SmallFlower00: { hash: 0x41f6dc87, type: DataType.BoolArray },
          SmallFlower01: { hash: 0xdfb7e2e7, type: DataType.BoolArray },
          SmallFlower02: { hash: 0x90cf7c09, type: DataType.BoolArray },
          SmallFlower03: { hash: 0x2877d719, type: DataType.BoolArray },
          SmallFlower04: { hash: 0xf21124c7, type: DataType.BoolArray },
          SmallFlower05: { hash: 0xdf67c433, type: DataType.BoolArray },
          SmallFlower06: { hash: 0x98563f49, type: DataType.BoolArray },
          SmallFlower07: { hash: 0x38086fc9, type: DataType.BoolArray },
          Snow00: { hash: 0xfd26fc1d, type: DataType.BoolArray },
          Stadium00: { hash: 0x4897c86e, type: DataType.BoolArray },
          Stadium01: { hash: 0x4dc81570, type: DataType.BoolArray },
          Stadium02: { hash: 0x15ee1f37, type: DataType.BoolArray },
          Stage00: { hash: 0xc2642dcd, type: DataType.BoolArray },
          StainedGlass00: { hash: 0x2c3d1596, type: DataType.BoolArray },
          StainedGlass01: { hash: 0xa9428b44, type: DataType.BoolArray },
          StainedGlass02: { hash: 0xe3da6f31, type: DataType.BoolArray },
          StarPrint00: { hash: 0xbb1f945e, type: DataType.BoolArray },
          StarPrint01: { hash: 0xe3c51ece, type: DataType.BoolArray },
          StarPrint02: { hash: 0x11890a2e, type: DataType.BoolArray },
          StarPrint03: { hash: 0xac3c79cf, type: DataType.BoolArray },
          StarPrint04: { hash: 0xcf09885a, type: DataType.BoolArray },
          Steampunk00: { hash: 0xd6372ebd, type: DataType.BoolArray },
          Strata00: { hash: 0xd7c213f7, type: DataType.BoolArray },
          Street00: { hash: 0x7b1b1ebe, type: DataType.BoolArray },
          Stuffed00: { hash: 0x0ba106ee, type: DataType.BoolArray },
          Stuffed01: { hash: 0x13b38ed2, type: DataType.BoolArray },
          Stuffed02: { hash: 0x0a9e9041, type: DataType.BoolArray },
          Stuffed03: { hash: 0x2d4956d0, type: DataType.BoolArray },
          Success00: { hash: 0x04d0101e, type: DataType.BoolArray },
          Sushi00: { hash: 0xb71c0ef8, type: DataType.BoolArray },
          Temple00: { hash: 0xac434d38, type: DataType.BoolArray },
          Train00: { hash: 0xdf8527a0, type: DataType.BoolArray },
          Train01: { hash: 0x59fddbba, type: DataType.BoolArray },
          Training00: { hash: 0x0272f85b, type: DataType.BoolArray },
          Triangle00: { hash: 0xa2a89c58, type: DataType.BoolArray },
          Triangle01: { hash: 0x057e2814, type: DataType.BoolArray },
          Triangle02: { hash: 0xcdbc2236, type: DataType.BoolArray },
          Triangle03: { hash: 0xcfe5ccb5, type: DataType.BoolArray },
          Triangle04: { hash: 0xb24461e7, type: DataType.BoolArray },
          Triangle05: { hash: 0xeca778ff, type: DataType.BoolArray },
          TropicalSea00: { hash: 0xc4fe9606, type: DataType.BoolArray },
          Wedding00: { hash: 0x57e21499, type: DataType.BoolArray },
          Wedding01: { hash: 0xbdf77db9, type: DataType.BoolArray },
          Wedding02: { hash: 0x45ade8eb, type: DataType.BoolArray },
          Wedding03: { hash: 0x92cc4c4a, type: DataType.BoolArray },
          Western00: { hash: 0x9a0445f9, type: DataType.BoolArray },
          WesternStyle00: { hash: 0xc7e851f4, type: DataType.BoolArray },
          WesternStyle01: { hash: 0xcc568b08, type: DataType.BoolArray },
          WesternStyle02: { hash: 0xca695b8c, type: DataType.BoolArray },
          WesternStyle03: { hash: 0xe27329b5, type: DataType.BoolArray },
          WesternStyle04: { hash: 0x9aef2924, type: DataType.BoolArray },
          WesternStyle05: { hash: 0xc734a9ff, type: DataType.BoolArray },
          WesternStyle06: { hash: 0xcedf80e9, type: DataType.BoolArray },
          WesternStyle07: { hash: 0x8f3b56da, type: DataType.BoolArray },
          WhiteRoom00: { hash: 0x1de47db2, type: DataType.BoolArray },
          WoodBoard00: { hash: 0x67523088, type: DataType.BoolArray },
          WoodBoard01: { hash: 0xb57110d1, type: DataType.BoolArray },
          WoodBoard02: { hash: 0x132928a2, type: DataType.BoolArray },
          WoodBoard03: { hash: 0xc95630dd, type: DataType.BoolArray },
          WoodBoard04: { hash: 0x5044b85a, type: DataType.BoolArray },
          WoodBoard05: { hash: 0x04212545, type: DataType.BoolArray },
          WoodBoard06: { hash: 0xddf2c323, type: DataType.BoolArray },
          WoodBoard07: { hash: 0xfcdcffb4, type: DataType.BoolArray },
          Wrestling00: { hash: 0xe7526de3, type: DataType.BoolArray },
        },
      },
      UgcClothOwnInfo: { hash: 0x68856f93, type: DataType.BoolArray },
      UgcExteriorOwnInfo: { hash: 0xdc1d18c0, type: DataType.BoolArray },
      UgcHeadwearOwnInfo: { hash: 0x9a6ba7dc, type: DataType.BoolArray },
      UgcInteriorOwnInfo: { hash: 0x7eb955c7, type: DataType.BoolArray },
    },
    CharInfoEx: { hash: 0x881ca27a, type: DataType.BinaryArray },
    CharacterParam: {
      Activeness: { hash: 0x25b48224, type: DataType.IntArray },
      Audaciousness: { hash: 0xcd8dbaf8, type: DataType.IntArray },
      Commonsense: { hash: 0x607ba160, type: DataType.IntArray },
      Gaiety: { hash: 0x68e1134e, type: DataType.IntArray },
      Sociability: { hash: 0x43cd364f, type: DataType.IntArray },
    },
    Feeling: {
      FeelingEndGameTime: { hash: 0x8f8161d5, type: DataType.UInt64Array },
      MiiHistoryId: { hash: 0x523402f6, type: DataType.Int64Array },
      Type: { hash: 0x176c29eb, type: DataType.EnumArray, options: FEELING },
    },
    HomeLiveTime: {
      CacheMapId: { hash: 0x3cbd9978, type: DataType.IntArray },
      CacheOwnerNum: { hash: 0xd7070113, type: DataType.IntArray },
      StartLiveTogetherTime: { hash: 0x34190cdf, type: DataType.UInt64Array },
    },
    Location: {
      HouseMapId: { hash: 0xb8ab3cac, type: DataType.IntArray },
      RoomIndex: { hash: 0xfc296601, type: DataType.IntArray },
    },
    MiiMisc: {
      BalloonTalkInfo: {
        LastTalkGameTime: { hash: 0xecf86ffb, type: DataType.UInt64Array },
        LastTalkHistoryId: { hash: 0x6bef9887, type: DataType.Int64Array },
      },
      BirthdayInfo: {
        AgeType: { hash: 0x46d52648, type: DataType.EnumArray, options: AGE_TYPE },
        BackupHeightBeforeSpray: { hash: 0x75b0a7fd, type: DataType.IntArray },
        Day: { hash: 0xab8ae08b, type: DataType.IntArray },
        DirectAge: { hash: 0x2545e583, type: DataType.IntArray },
        Month: { hash: 0x6cf484f4, type: DataType.IntArray },
        SprayType: { hash: 0x546f4c99, type: DataType.EnumArray, options: AGE_TYPE_OPTIONAL },
        Year: { hash: 0x5d7d3f45, type: DataType.IntArray },
      },
      BondInfo: {
        IsUnlockPlayerNickName: { hash: 0xe0b5e5a1, type: DataType.BoolArray },
        Meter: { hash: 0xd0882636, type: DataType.IntArray },
      },
      ClothInfo: {
        Accessory: {
          ColorIndex: { hash: 0x64af701a, type: DataType.IntArray },
          KeyHash: { hash: 0xc1094d9f, type: DataType.UIntArray },
        },
        All: {
          ColorIndex: { hash: 0xee37f256, type: DataType.IntArray },
          KeyHash: { hash: 0xb20feced, type: DataType.UIntArray },
        },
        BottomsA: {
          ColorIndex: { hash: 0xec5010fb, type: DataType.IntArray },
          KeyHash: { hash: 0x15aea81d, type: DataType.UIntArray },
        },
        BottomsB: {
          ColorIndex: { hash: 0x536dbec2, type: DataType.IntArray },
          KeyHash: { hash: 0x7a1809d1, type: DataType.UIntArray },
        },
        BottomsUGCIndex: { hash: 0xf816f065, type: DataType.IntArray },
        ClothStyle: { hash: 0x660c5247, type: DataType.EnumArray, options: CLOTH_STYLE_GENDER },
        Coordinate: {
          ColorIndex: { hash: 0x763c97cc, type: DataType.IntArray },
          KeyHash: { hash: 0xd5ee521a, type: DataType.UIntArray },
        },
        Headwear: {
          ColorIndex: { hash: 0xc499cda5, type: DataType.IntArray },
          KeyHash: { hash: 0x98cc9ccc, type: DataType.UIntArray },
        },
        HeadwearUGCIndex: { hash: 0x8474b9d7, type: DataType.IntArray },
        IsTopsIn: { hash: 0xd6ad0e0b, type: DataType.BoolArray },
        NextClothWantGameTime: { hash: 0x1c535dac, type: DataType.UInt64Array },
        Shoes: {
          ColorIndex: { hash: 0xc0529e53, type: DataType.IntArray },
          KeyHash: { hash: 0x0a903d03, type: DataType.UIntArray },
        },
        Tops: {
          ColorIndex: { hash: 0x77cf0ff7, type: DataType.IntArray },
          KeyHash: { hash: 0xe81ee9c4, type: DataType.UIntArray },
        },
        TopsUGCIndex: { hash: 0xe3802eb9, type: DataType.IntArray },
        Topslong: {
          ColorIndex: { hash: 0x1124095d, type: DataType.IntArray },
          KeyHash: { hash: 0x35256740, type: DataType.UIntArray },
        },
      },
      EatInfo: {
        BestId: { hash: 0x5409455d, type: DataType.UIntArray },
        EatFullness: { hash: 0xef25b456, type: DataType.IntArray },
        GivenFlag: { hash: 0xfe434951, type: DataType.BinaryArray },
        GivenUgcFlag: { hash: 0xc022c1ae, type: DataType.BinaryArray },
        LastEatId: {
          Id: { hash: 0x36dcef14, type: DataType.UIntArray },
          UgcIndex: { hash: 0xa08abd36, type: DataType.IntArray },
        },
        LastFoodGiveTime: { hash: 0x0fcb2a3d, type: DataType.UInt64Array },
        RankedFoodId: {
          Id: { hash: 0xfbd391d9, type: DataType.UIntArray },
          UgcIndex: { hash: 0x957930c4, type: DataType.IntArray },
        },
        TasteType: { hash: 0xb69b048c, type: DataType.IntArray },
        UltraBestId: { hash: 0x21eea734, type: DataType.UIntArray },
        UltraWorstId: { hash: 0x5c7cd87a, type: DataType.UIntArray },
        WorstId: { hash: 0x400e8774, type: DataType.UIntArray },
      },
      EntryInfo: {
        BloodMiiIndex: { hash: 0xf4db66f3, type: DataType.IntArray },
        HowToCallPlayerNickName: { hash: 0x80eefca9, type: DataType.WString64Array },
        IsChildInGame: { hash: 0x8aff821b, type: DataType.BoolArray },
        NewEntryGameTime: { hash: 0x2b881856, type: DataType.UInt64Array },
        PlayerNickName: { hash: 0x8311da48, type: DataType.WString32Array },
        PlayerNickNameRegionLanguageID: {
          hash: 0x4a9343c4,
          type: DataType.EnumArray,
          options: LANGUAGE,
        },
        SortIndex: { hash: 0x9ccf22b7, type: DataType.IntArray },
      },
      FaceInfo: {
        FacePaintIndex: { hash: 0x5e32adf4, type: DataType.IntArray },
        Gender: { hash: 0x236e2d73, type: DataType.EnumArray, options: MII_GENDER },
        HairChangeGameTime: { hash: 0xcb6830ca, type: DataType.UInt64Array },
        HairChangeOrdered: { hash: 0xafed53d6, type: DataType.IntArray },
        IsDoneHairChangeTalk: { hash: 0x5a4f133a, type: DataType.BoolArray },
        IsFacePaintFront: { hash: 0xde73cee6, type: DataType.BoolArray },
        IsLoveGender: { hash: 0xdfc82223, type: DataType.BoolArray },
        IsSelectedGoodHairChangeTalk: { hash: 0x9959aeea, type: DataType.BoolArray },
        PrevHairChangeCharInfo: { hash: 0xf13124bd, type: DataType.BinaryArray },
        ReadyHairChangeGameTime: { hash: 0x819d8134, type: DataType.UInt64Array },
        RejectHairChangeGameTime: { hash: 0x4d27e120, type: DataType.UInt64Array },
      },
      PatInfo: {
        LastPatGameTime: { hash: 0x4658aaed, type: DataType.UInt64Array },
      },
      SatisfyInfo: {
        DepressGameTime: { hash: 0xdd5e39ef, type: DataType.UInt64Array },
        LastMiiTouchGameTime: { hash: 0xc0b2d7fe, type: DataType.UInt64Array },
        Level: { hash: 0x9999b7d9, type: DataType.IntArray },
        Meter: { hash: 0x197237e7, type: DataType.IntArray },
      },
      SleepInfo: {
        HasDream: { hash: 0x75bd7c16, type: DataType.BoolArray },
        WakeUpTime: { hash: 0x54346174, type: DataType.UInt64Array },
      },
      UgcInfo: {
        IsCopy: { hash: 0xdbdb59fa, type: DataType.BoolArray },
        IsEdit: { hash: 0x7f9b5d34, type: DataType.BoolArray },
        IsNeedPutHouseLocalNetwork: { hash: 0x4613c6a7, type: DataType.BoolArray },
        IslandName: { hash: 0xd8d889e2, type: DataType.WString32Array },
        IslandNameRegionLanguageID: {
          hash: 0xc903c025,
          type: DataType.EnumArray,
          options: LANGUAGE,
        },
        NetworkDeliverCount: { hash: 0x62aaaa12, type: DataType.UIntArray },
        NetworkUuid: { hash: 0xdc260809, type: DataType.String64Array },
        PlayerName: { hash: 0x570f552e, type: DataType.WString32Array },
        PlayerNameRegionLanguageID: {
          hash: 0xac9950ed,
          type: DataType.EnumArray,
          options: LANGUAGE,
        },
      },
      WordInfo: {
        WordArray: {
          WordHowToCall: { hash: 0x0b2a261e, type: DataType.WString64Array },
          WordKind: { hash: 0x5f7bfcc8, type: DataType.EnumArray, options: WORD_KIND },
          WordRegionLanguageID: { hash: 0x843ba2fe, type: DataType.EnumArray, options: LANGUAGE },
          WordText: { hash: 0x09ef8656, type: DataType.WString64Array },
        },
      },
    },
    Name: {
      FirstPerson: { hash: 0x2471a0ca, type: DataType.WString32Array },
      FirstPersonPresetIndex: { hash: 0xfa3e5c01, type: DataType.IntArray },
      FirstPersonRegionLanguageID: {
        hash: 0x2c8f9762,
        type: DataType.EnumArray,
        options: LANGUAGE,
      },
      HowToCallFirstPerson: { hash: 0x52cdea08, type: DataType.WString64Array },
      HowToCallName: { hash: 0x3a5eda05, type: DataType.WString64Array },
      Name: { hash: 0x2499bfda, type: DataType.WString32Array },
      NameRegionLanguageID: { hash: 0x715ab967, type: DataType.EnumArray, options: LANGUAGE },
      PronounType: { hash: 0xf3c3de59, type: DataType.EnumArray, options: PRONOUN },
    },
    Trouble: {
      ChildBirthBlockTime: { hash: 0x44b5a140, type: DataType.UInt64Array },
      Info: {
        EndGameTime: { hash: 0x614f54b8, type: DataType.UInt64Array },
        Id: { hash: 0x970906fc, type: DataType.UIntArray },
        IsFirstDemoDone: { hash: 0x032bfb74, type: DataType.BoolArray },
        NextGameTime: { hash: 0xd4642e9f, type: DataType.UInt64Array },
        TargetClothId: { hash: 0xc1ea241c, type: DataType.UIntArray },
        TargetCoordinateId: { hash: 0xbf9889c4, type: DataType.UIntArray },
        TargetFoodId: { hash: 0xfbe430b7, type: DataType.UIntArray },
        TargetGoodsId: { hash: 0x07a75771, type: DataType.UIntArray },
        TargetItemType: { hash: 0x8daed276, type: DataType.IntArray },
        TargetMapObject: {
          GridPosX: { hash: 0x4fc817b6, type: DataType.IntArray },
          GridPosY: { hash: 0x30e34a3a, type: DataType.IntArray },
          MapObjectId: { hash: 0x960a6e3b, type: DataType.UIntArray },
        },
        TargetMiiIndex: { hash: 0x9c5a11d1, type: DataType.IntArray },
        TargetPresetIndex: { hash: 0x1bb29cb5, type: DataType.IntArray },
        TargetUgcFoodIndex: { hash: 0xa1760cdc, type: DataType.IntArray },
        TargetUgcGoodsIndex: { hash: 0xa4be088b, type: DataType.IntArray },
        TargetUgcTextIndex: { hash: 0x3b45572e, type: DataType.IntArray },
      },
    },
    Voice: {
      Formant: { hash: 0x4913ae1a, type: DataType.IntArray },
      Intonation: { hash: 0x07b9d175, type: DataType.IntArray },
      Pitch: { hash: 0x81cf470a, type: DataType.IntArray },
      PresetType: { hash: 0xfbc3ffb0, type: DataType.EnumArray, options: VOICE_PRESET },
      Speed: { hash: 0x141ee086, type: DataType.IntArray },
      Tension: { hash: 0x4d78e262, type: DataType.IntArray },
    },
  },
  Relation: {
    BoostEndFlag: { hash: 0x3e309f67, type: DataType.BoolArray },
    Info: {
      DirectionalInfo: {
        BaseRelationType: { hash: 0x8b41897e, type: DataType.EnumArray, options: RELATION },
        BitFlag: { hash: 0x24433fbe, type: DataType.UIntArray },
        BloodType: { hash: 0x77d6afce, type: DataType.EnumArray, options: FAMILY_RELATION },
        Meter: { hash: 0x42c2fc2f, type: DataType.IntArray },
        NameSetBin: { hash: 0xafa5024a, type: DataType.BinaryArray },
        NickNameToOtherType: { hash: 0xa0058500, type: DataType.EnumArray, options: ADDRESS_FORM },
        SecondPersonRegionLanguageID: {
          hash: 0x96aa92d5,
          type: DataType.EnumArray,
          options: LANGUAGE,
        },
        ThirdPersonRegionLanguageID: {
          hash: 0x2b87527f,
          type: DataType.EnumArray,
          options: LANGUAGE,
        },
        UpdateTimeRanking: { hash: 0x5b9181eb, type: DataType.UInt64Array },
      },
      IsFight: { hash: 0xc2db3a72, type: DataType.BoolArray },
      IsNotifiedBloodTypeCouple: { hash: 0x6e00ce64, type: DataType.BoolArray },
      RelationId: {
        Id_a: { hash: 0xf7420afb, type: DataType.IntArray },
        Id_b: { hash: 0x4071f71c, type: DataType.IntArray },
      },
      TypeSetTime: { hash: 0x1a892e50, type: DataType.UInt64Array },
    },
  },
  Unknown: {
    '0xFA21F70E': { hash: 0xfa21f70e, type: DataType.BoolArray },
  },
} as const;

export const MII_SCHEMA = _MII_SCHEMA;
